FROM node:18-alpine

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN npx prisma generate

RUN yarn build

EXPOSE 3000

ENV HOST=0.0.0.0
ENV WATCHPACK_POLLING true

CMD ["yarn", "dev"]